name: customer_request_application
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter
  http: ^1.3.0
  mysql_client: ^0.0.27
  path: ^1.9.0
  provider: ^6.1.2
  sqflite: ^2.4.1
  mysql1: ^0.20.0
  signature: ^5.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
