name: customer_request_application
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter
  http: ^1.3.0
  mysql_client: ^0.0.27
  path: ^1.9.0
  provider: ^6.1.2
  sqflite: ^2.4.1
  mysql1: ^0.20.0
  signature: ^5.5.0
  image: ^4.5.3
  pdf: ^3.6.0 # Per generare PDF
  pdf_render: ^1.4.12
  path_provider: ^2.0.8 # Per salvare il PDF nel file system
  syncfusion_flutter_pdf: ^20.1.59

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
  - assets/resources/image/
  - assets/resources/Documents/ResguardoDeposito.pdf
